name: commit_message_checker

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:

  deploy-qa:
    if: contains(github.event.pull_request.body, '/deploy ')
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract QA Environment
      id: extract-env
      uses: actions/github-script@v6
      with:
        script: |
          const body = context.payload.pull_request.body
          const match = body.match(/\/deploy\s+(\w+)/);
          const env = match ? match[1] : '';
          core.setOutput('env', env);

    - name: Deploy to QA Environment
      if: steps.extract-env.outputs.env != ''
      run: |
        echo "Deploying to QA environment: ${{ steps.extract-env.outputs.env }}"
        # Add your deployment script/commands here





